# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/read_pdz',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/read_pdz',
                'lib_path': 'read_pdz'},
  'syms': {}}
